# -*- coding: utf-8 -*-
"""RPL1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZEUc8yV8-5zD7Wx41UIp1JnWff_EQ7G6
"""

import pandas as pd

data ={"padron":[10,20,30,20,50,30,50,50,30,70],"materia":["A","B","D","B","K","D","K","H","K","A"],"nota":[5,6,3,6,2,9,9,6,7,4],"fecha":["11-09-2020","11-04-2020","13-08-2020","11-04-2020","16-04-2020","11-09-2020","11-09-2020","11-04-2019","16-04-2019","11-09-2019"]}

df = pd.DataFrame(data)
df.head(10)

"""Promedio General"""

promedio = df["nota"].sum()/len(df)
promedio

"""Nota Max y Min del 2019

"""

df["fecha"] = pd.to_datetime(df["fecha"])
notas_2019 = df[(df["fecha"].dt.year == 2019)]

nota_max = notas_2019["nota"].max()
nota_min = notas_2019["nota"].min()
max_min =  (nota_max,nota_min)
max_min

"""Padron con mayor cantidad de materias aprobadas durante el ultimo cuatrimestre"""

#me quedo con las del segundo cuatrimestre
ultimo_cuatrimestre = df[(df["fecha"].dt.month> 4)]
ultimo_cuatrimestre =df[(df["fecha"].dt.year ==  2020)]
ultimo_cuatrimestre

#me quedo con padron y nota nomas
padron_nota = ultimo_cuatrimestre[["padron","nota"]]
#me quedo con las filas de notas aprobadas
padron_notas_aprobadas = padron_nota[padron_nota["nota"]>=4]
#me quedo con el indice que tenga mayor cantidad de ocurrencias (notas arpobadas)
mas_aprobadas = padron_notas_aprobadas["padron"].value_counts().nlargest(1).index[0]
mas_aprobadas

"""Nota promedio por materia"""

materias_nota = df[["materia","nota"]]
materias_nota_grouped = materias_nota.groupby("materia").agg({"nota":"mean"})
materias_nota_grouped.to_dict()

"""nota promedio por padron"""

padron_nota = df[["padron","nota"]]
padron_nota_grouped = padron_nota.groupby("padron").agg({"nota":"mean"})
padron_nota_grouped.to_dict()