# -*- coding: utf-8 -*-
"""Finger1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mb9nHnp8n4udtDwvnbB90ApoJKpwXnuC
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import drive 
drive.mount('/content/gdrive')
# %matplotlib inline

"""# **Cargo DataFrame desde el drive**


"""

country_vacc = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/country_vacc.csv")
country_vacc.head()

"""# **Me quedo con las columnas paises y gente vacunada**"""

country_vacc_total_vacc = country_vacc[["country","people_vaccinated"]]

"""# **Ordeno por pais y sumo las vacunas totales**"""

grouped = country_vacc_total_vacc.groupby(["country"]).agg({"people_vaccinated":"sum"})
grouped.people_vaccinated.nlargest(1)

#Hago DF con pais, vacunados totales y vacunados con una sola dosis
country_vacc_people_fully = country_vacc[["country","people_vaccinated","people_fully_vaccinated"]]


#agrupo por pais, quedandome el total de vacunados de cada pais (parcial o completamente)
grouped = country_vacc_people_fully.groupby("country").agg({"people_vaccinated":"sum","people_fully_vaccinated":"sum"})
#me quedo con los 10 paises que mas vacunados tienen
TopTen = grouped.nlargest(10,"people_vaccinated")

#Normalizo, lo que me interesa es que porcentaje de la poblacion vacunada lo está completamente
#los vacunados parciales son los totales menos los completamente vacunados sobre los totales
TopTen["partially_vaccinated"] = (TopTen["people_vaccinated"]-TopTen["people_fully_vaccinated"])/TopTen["people_vaccinated"]
#lo completamente vacunados solo los divido por los totales para normalizar
TopTen["people_fully_vaccinated"] = TopTen["people_fully_vaccinated"]/TopTen["people_vaccinated"]

#no preciso mas esta columna
del TopTen["people_vaccinated"]

#ploteo
TopTen.plot.bar(rot=45,stacked=True,color={"people_fully_vaccinated":"blue","partially_vaccinated":"gold"},figsize=(15,8))