# -*- coding: utf-8 -*-
"""s 2020-2C - 1er Recuperatorio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I0Ubjfg5FyLBDSa2NqN-6I942K4828-3

Una compañía de logística de insumos médicos es responsable de toda la cadena de
abastecimiento de estos a hospitales. Esto se ha vuelto crítico en los últimos meses para asistir
al personal médico en su lucha contra la pandemia. La logística se realiza sobre categorías de
productos que se preparan en lotes (en pallets) que son entregados a las instituciones médicas.
Es por ello que cuentan con información en los siguientes archivos csv:
lote.csv (id_lote, fecha_programada_entrega, id_destino, descripcion,
id_categoria_insumo, cantidad_de_unidades_insumo)
destinos.csv (id_destino, nombre, atencion_critica, region, latitud,
longitud)
categorias_insumos.csv (id_categoria_insumo, nombre, uso_esencial)
El primer archivo cuenta con información de los lotes de insumos a entrega, indicando la fecha
programada de entrega (en formato “YYYY-mm-dd”), cual es el destino al que se va a realizar
la entrega (id_destino), una descripción del contenido del lote y cantidad de unidades del
insumo que se encuentran en el lote.
Además se aporta información de la categoría a la que corresponde el insumo.
Por otro lado se tiene información sobre los distintos destinos en los que se deben entregar los
insumos, su nombre, a que región pertenece, latitud y longitud.
Se cuenta también con un indicador booleano que indica si ese destino es un centro de
atencion crítica.
En el último archivo, contamos con la información de las distintas categorías de insumos,
indicando el nombre de la categoría y la columna booleana "uso_esencial" que nos indica
que el producto de esa categoría de insumo es de uso esencial.
Se desea:

a) Listar los nombres de 10 destinos de la región de “CABA” que durante el mes de septiembre
recibieron la mayor cantidad de lotes de insumos de uso esencial.

b) Listar el resumen del plan de entregas para la transportadora del dia de hoy.
Este debe tener el siguiente formato (fecha_programada_entrega,
nombre_destino, cantidad_de_lotes_a_entregar).
A su vez debe estar ordenado de tal forma que primero estén listados aquellos destinos
que son de atención crítica.
"""

import pandas as pd

lote = pd.DataFrame({"id_lote":["A01","A02","A04","A05","A06"],
                     "fecha_programada_entrega":["2020-7-22","2020-9-21","2020-9-21","2020-12-22","2020-9-21"],
                     "id_destino":[1,2,3,4,6],
                     "descripcion":["a","a","a","a","a"],
                     "id_categoria_insumo":["b01","b03","b04","b05","b06"],
                     "cantidad_de_unidades_insumo":[1,2,3,4,5]
                     })
destinos = pd.DataFrame({"id_destino":[1,2,3,4,5,6],
                         "nombre":["a","a","a","a","a","a"],
                         "atencion_critica":[True,True,False,True,False,True],
                         "region":["CABA","CABA","NOCABA","CABA","CABA","CABA"],
                         "latitud":[1,2,3,4,5,6],
                         "longitud":[1,2,3,4,5,6]
                         })
categorias_insumos = pd.DataFrame({"id_categoria_insumo":["b01","b02","b03","b04","b05","b06"],
                                   "nombre":["a","b","c","d","e","f"],
                                   "uso_esencial":[True,True,False,True,False,True]})

"""**Listar los nombres de 10 destinos de la región de “CABA” que durante el mes de septiembre recibieron la mayor cantidad de lotes de insumos de uso esencial.**"""

region_caba = destinos[destinos["region"]=="CABA"]
region_caba

lote

lotes_a_caba = region_caba.merge(lote,how="left")
lotes_a_caba

insumos_esenciales = categorias_insumos[categorias_insumos["uso_esencial"]==True]
insumos_esenciales

lotes_a_caba_esenciales = insumos_esenciales.merge(lotes_a_caba,how="inner")
lotes_a_caba_esenciales

lotes_a_caba_esenciales_septiembre = lotes_a_caba_esenciales[pd.to_datetime(lotes_a_caba_esenciales["fecha_programada_entrega"]).dt.month == 9]
lotes_a_caba_esenciales_septiembre
#Aca iria un nlargest y quedarme con los nombres

"""**Listar el resumen del plan de entregas para la transportadora del dia de hoy. Este debe tener el siguiente formato (fecha_programada_entrega, nombre_destino, cantidad_de_lotes_a_entregar). A su vez debe estar ordenado de tal forma que primero estén listados aquellos destinos que son de atención crítica.**"""

lotes_hoy = lote[pd.to_datetime(lote["fecha_programada_entrega"]).dt.day==21]
lotes_hoy

lotes_hoy_con_destino = lotes_hoy.merge(destinos,how="inner")
lotes_hoy_con_destino

lotes_hoy_con_destino_critico = lotes_hoy_con_destino.sort_values(by=["atencion_critica"],ascending=False)
lotes_hoy_con_destino_critico

ptoB = lotes_hoy_con_destino_critico[["fecha_programada_entrega","nombre","cantidad_de_unidades_insumo"]]
ptoB.columns = ["fecha_programada_entrega", "nombre_destino", "cantidad_de_lotes_a_entregar"]
ptoB